<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>The James & Andy Show playlist for Friday, November 16, 2012, 16:00</title>
<style type="text/css">
@import url(wprb.css);
h2	{ color:#FFFFFF }
h3 { color: #FFFFFF; line-height:.5 }
.text { color: #FFFFFF }
a { color: #FFFFFF }
b { color: #FFFFFF }
.black { color: #FFFFFF }
</style>

<script language="JavaScript" src="jscripts.js"></script>
</head>
<body bgcolor="#000000" text="#FFFFFF" 
		link="#FFFFFF" vlink="#FFFFFF">

<!-- ************ REMOVABLE ************ -->
<div class='text'>
<!-- Theis Playlist Manager navigation toolbar -->
<a href = "http://www.wprb.com" target="_top">wprb home</a> |
<a href = "listen.php">listen live</a> |
<a href = "currentplaylist.php">current playlist</a> |
<a href = "wprb_schedule.php">schedule</a>	|
<a href = "wprb_djlist.php">dj list</a> |
<a href = "wprb_last10.php">last 10 days</a> |
<a href = "wprb_search.php">search</a> |
<a href = "http://pledge.wprb.com">donate to wprb</a><br>
</div><p>
<!-- ********** END REMOVABLE ********** -->

<h2>The James & Andy Show</h2><h3></h3>
<h3> with James & Andy</h3>
<span class='text'><a href="djplaylists.php?id=380">other shows</a></span><p>
<span class='text'>Friday, November 16, 2012<br>
16:00 to 18:00<br>Electro, Rock and Hip Hop<br>
</span><span class='text'>
	<a href='http://www.facebook.com/pages/The-James-Andy-Show/178662928883702?sk=wall'>http://www.facebook.com/pages/The-James-Andy-Show/178662928883702?sk=wall</a></text><p><table cellpadding='3' width='*'>
	<tr>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Artist</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Song</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Album</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Label</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>New</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Request</font></th>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Jack Dixon</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>E</font></td>
		<td class='mid' bgcolor="#EEEEEE">E/Find Shelter</td>
		<td class='mid' bgcolor="#EEEEEE">Hotflush</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Flume</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Sintra</font></td>
		<td class='mid' bgcolor="#EEEEEE">s/t</td>
		<td class='mid' bgcolor="#EEEEEE">Future Classic</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Teengirl Fantasy</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Floor to floor</font></td>
		<td class='mid' bgcolor="#EEEEEE">7AM</td>
		<td class='mid' bgcolor="#EEEEEE">True Panther US</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Flying Lotus</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Electric Candyman</font></td>
		<td class='mid' bgcolor="#EEEEEE">Until the Quiet Comes</td>
		<td class='mid' bgcolor="#EEEEEE">Warp</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Samoyed</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Minnow</font></td>
		<td class='mid' bgcolor="#EEEEEE">VSE07</td>
		<td class='mid' bgcolor="#EEEEEE">Vase</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Four Tet</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Love Cry (Joy Orbison Remix)</font></td>
		<td class='mid' bgcolor="#EEEEEE">Angel Echoes + Remixes</td>
		<td class='mid' bgcolor="#EEEEEE">Domino</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Gold Panda</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>You (Osborne Remix)</font></td>
		<td class='mid' bgcolor="#EEEEEE">You EP</td>
		<td class='mid' bgcolor="#EEEEEE">Ghostly International</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">The Orb feat. Lee "Scratch" Perry</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Soulman</font></td>
		<td class='mid' bgcolor="#EEEEEE">The Orbserver in the Star House</td>
		<td class='mid' bgcolor="#EEEEEE">Cooking Vinyl/The End</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">DJ Tennis feat. Pillowtalk</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>The Outcast</font></td>
		<td class='mid' bgcolor="#EEEEEE">The Outcast</td>
		<td class='mid' bgcolor="#EEEEEE">Kompakt</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Trust</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>The Last Dregs</font></td>
		<td class='mid' bgcolor="#EEEEEE">TRST</td>
		<td class='mid' bgcolor="#EEEEEE">Arts & Crafts</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Matthew Dear</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Her Fantasy (Tornado Wallace Remix)</font></td>
		<td class='mid' bgcolor="#EEEEEE">Her Fantasy single</td>
		<td class='mid' bgcolor="#EEEEEE">Ghostly International</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Com Truise</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Sundriped</font></td>
		<td class='mid' bgcolor="#EEEEEE">Cyanide Sisters LP</td>
		<td class='mid' bgcolor="#EEEEEE">Ghostly International</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Falty DL</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Straight and Arrow (Radio Edit)</font></td>
		<td class='mid' bgcolor="#EEEEEE">Straight and Arrow</td>
		<td class='mid' bgcolor="#EEEEEE">Ninja Tune</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Calibro 35</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>The Package</font></td>
		<td class='mid' bgcolor="#EEEEEE">Any Resemblance to Real Persons or Actual Facts is Purely Coincidental</td>
		<td class='mid' bgcolor="#EEEEEE">Nublu Records</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">The Chemical Brothers</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Do it Again</font></td>
		<td class='mid' bgcolor="#EEEEEE">Brotherhood</td>
		<td class='mid' bgcolor="#EEEEEE">Astralwerks</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">The 2 Bears</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Bear Hug</font></td>
		<td class='mid' bgcolor="#EEEEEE">Be Strong</td>
		<td class='mid' bgcolor="#EEEEEE">Souther Fried/DFA</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Jimmy Edgar</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Let Yrself Be</font></td>
		<td class='mid' bgcolor="#EEEEEE">Majenta</td>
		<td class='mid' bgcolor="#EEEEEE">Hotflush</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">MNDR</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Faster Horses</font></td>
		<td class='mid' bgcolor="#EEEEEE">Feed Me Diamonds</td>
		<td class='mid' bgcolor="#EEEEEE">Ultra Records</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Photek</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Shape Charge</font></td>
		<td class='mid' bgcolor="#EEEEEE">KU:PALM</td>
		<td class='mid' bgcolor="#EEEEEE">Photek Productions</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Gold Panda</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Snow and Taxis</font></td>
		<td class='mid' bgcolor="#EEEEEE">Lucky Shiner</td>
		<td class='mid' bgcolor="#EEEEEE">Ghostly International</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>R</font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Lapalux</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Quartz</font></td>
		<td class='mid' bgcolor="#EEEEEE">Some Other Time EP</td>
		<td class='mid' bgcolor="#EEEEEE">Brainfeeder</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Dan Deacon</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>True Thrush</font></td>
		<td class='mid' bgcolor="#EEEEEE">America</td>
		<td class='mid' bgcolor="#EEEEEE">Domino</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
</table>
<p class='text'>
<!-- Theis Playlist Manager navigation toolbar -->
<a href = "http://www.wprb.com" target="_top">wprb home</a> |
<a href = "listen.php">listen live</a> |
<a href = "currentplaylist.php">current playlist</a> |
<a href = "wprb_schedule.php">schedule</a>	|
<a href = "wprb_djlist.php">dj list</a> |
<a href = "wprb_last10.php">last 10 days</a> |
<a href = "wprb_search.php">search</a> |
<a href = "http://pledge.wprb.com">donate to wprb</a><br>
</p>
</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-10029854-1']);
  _gaq.push(['_setDomainName', 'wprb.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</html>
