<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>The James & Andy Show playlist for Friday, November 30, 2012, 18:00</title>
<style type="text/css">
@import url(wprb.css);
h2	{ color:#FFFFFF }
h3 { color: #FFFFFF; line-height:.5 }
.text { color: #FFFFFF }
a { color: #FFFFFF }
b { color: #FFFFFF }
.black { color: #FFFFFF }
</style>

<script language="JavaScript" src="jscripts.js"></script>
</head>
<body bgcolor="#000000" text="#FFFFFF" 
		link="#FFFFFF" vlink="#FFFFFF">

<!-- ************ REMOVABLE ************ -->
<div class='text'>
<!-- Theis Playlist Manager navigation toolbar -->
<a href = "http://www.wprb.com" target="_top">wprb home</a> |
<a href = "listen.php">listen live</a> |
<a href = "currentplaylist.php">current playlist</a> |
<a href = "wprb_schedule.php">schedule</a>	|
<a href = "wprb_djlist.php">dj list</a> |
<a href = "wprb_last10.php">last 10 days</a> |
<a href = "wprb_search.php">search</a> |
<a href = "http://pledge.wprb.com">donate to wprb</a><br>
</div><p>
<!-- ********** END REMOVABLE ********** -->

<h2>The James & Andy Show</h2><h3></h3>
<h3> with James & Andy</h3>
<span class='text'><a href="djplaylists.php?id=380">other shows</a></span><p>
<span class='text'>Friday, November 30, 2012<br>
18:00 to 20:00<br>Electro, Rock and Hip Hop<br>
</span><span class='text'>
	<a href='http://www.facebook.com/pages/The-James-Andy-Show/178662928883702?sk=wall'>http://www.facebook.com/pages/The-James-Andy-Show/178662928883702?sk=wall</a></text><p><table cellpadding='3' width='*'>
	<tr>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Artist</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Song</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Album</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Label</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>New</font></th>
		<th bgcolor="#EEEEEE"> <font color='#000000'>Request</font></th>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">NeferTT</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Blue Skies Red Soil</font></td>
		<td class='mid' bgcolor="#EEEEEE">Blue Skies Red Soil EP</td>
		<td class='mid' bgcolor="#EEEEEE">Hotflush</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Flume</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Space Cadet</font></td>
		<td class='mid' bgcolor="#EEEEEE">S/T</td>
		<td class='mid' bgcolor="#EEEEEE">Future Classics</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Matthias Zimmermann</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Paul</font></td>
		<td class='mid' bgcolor="#EEEEEE">Botanica Dub EP</td>
		<td class='mid' bgcolor="#EEEEEE">Sound Pellegrino</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Grimes</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Oblivion</font></td>
		<td class='mid' bgcolor="#EEEEEE">Visions</td>
		<td class='mid' bgcolor="#EEEEEE">4AD</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Lone</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Moon Beam Harp</font></td>
		<td class='mid' bgcolor="#EEEEEE">Emerald Fantasy Tracks</td>
		<td class='mid' bgcolor="#EEEEEE">Magic Wire Recordings</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Blevin Blectum</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Mine</font></td>
		<td class='mid' bgcolor="#EEEEEE">Gular Flutter</td>
		<td class='mid' bgcolor="#EEEEEE">AAGOO</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Aphex Twin</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Donkey Rhubarb</font></td>
		<td class='mid' bgcolor="#EEEEEE">Donkey Rhubarb EP</td>
		<td class='mid' bgcolor="#EEEEEE">Warp Records</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Flying Lotus</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Do the Astral Plane</font></td>
		<td class='mid' bgcolor="#EEEEEE">Cosmogramma</td>
		<td class='mid' bgcolor="#EEEEEE">Warp Records</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Kraftwerk</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Radioactivity</font></td>
		<td class='mid' bgcolor="#EEEEEE">Radio-Activity</td>
		<td class='mid' bgcolor="#EEEEEE">Capitol Records</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Matthew Dear</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Her Fantasy (Tornado Wallace remix)</font></td>
		<td class='mid' bgcolor="#EEEEEE">Her Fantasy Single</td>
		<td class='mid' bgcolor="#EEEEEE">Ghostly International</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Child Actor</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Wait</font></td>
		<td class='mid' bgcolor="#EEEEEE">Victory</td>
		<td class='mid' bgcolor="#EEEEEE">Fake Four</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Mogwai</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Summer (priority version)</font></td>
		<td class='mid' bgcolor="#EEEEEE">Young Team</td>
		<td class='mid' bgcolor="#EEEEEE">rawk</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Egyptrixx</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Chrysalis Records</font></td>
		<td class='mid' bgcolor="#EEEEEE">Bible Eyes</td>
		<td class='mid' bgcolor="#EEEEEE">Night Slugs</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">LCD Soundsystem</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>All My Friends</font></td>
		<td class='mid' bgcolor="#EEEEEE">London Sessions</td>
		<td class='mid' bgcolor="#EEEEEE">DFA</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Letherette</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Ettewards</font></td>
		<td class='mid' bgcolor="#EEEEEE">Featurette</td>
		<td class='mid' bgcolor="#EEEEEE">Ninja Tune</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Washed Out</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>You and I</font></td>
		<td class='mid' bgcolor="#EEEEEE">Within and Without</td>
		<td class='mid' bgcolor="#EEEEEE">Sub Pop</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>R</font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Groundislava feat. Baths</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Suicide Mission</font></td>
		<td class='mid' bgcolor="#EEEEEE">Feel Me</td>
		<td class='mid' bgcolor="#EEEEEE">Friends of Friends</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Cat Power</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>3,6,9</font></td>
		<td class='mid' bgcolor="#EEEEEE">Sun</td>
		<td class='mid' bgcolor="#EEEEEE">Matador</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>*</font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Crystal Castles</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Pap Smear</font></td>
		<td class='mid' bgcolor="#EEEEEE">Crystal Castles</td>
		<td class='mid' bgcolor="#EEEEEE">Universal Motown</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>R</font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Happa</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Beat of the Drum (Throwing Snow remix)</font></td>
		<td class='mid' bgcolor="#EEEEEE">Beat of the Drum</td>
		<td class='mid' bgcolor="#EEEEEE">Church</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Tame Impala</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>I Don't Really Mind</font></td>
		<td class='mid' bgcolor="#EEEEEE">Innerspeaker</td>
		<td class='mid' bgcolor="#EEEEEE">Modular</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>R</font></td>
</font></td>
	</tr>
		<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#000000' colspan='8'></td></tr>
	<tr>
		<td class='mid' bgcolor="#EEEEEE">Simian Mobile Disco</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'>Pinball</font></td>
		<td class='mid' bgcolor="#EEEEEE">Temporary Pleasure</td>
		<td class='mid' bgcolor="#EEEEEE">Wichita</td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
		<td class='mid' bgcolor="#EEEEEE"><font color='#000000'></font></td>
</font></td>
	</tr>
</table>
<p class='text'>
<!-- Theis Playlist Manager navigation toolbar -->
<a href = "http://www.wprb.com" target="_top">wprb home</a> |
<a href = "listen.php">listen live</a> |
<a href = "currentplaylist.php">current playlist</a> |
<a href = "wprb_schedule.php">schedule</a>	|
<a href = "wprb_djlist.php">dj list</a> |
<a href = "wprb_last10.php">last 10 days</a> |
<a href = "wprb_search.php">search</a> |
<a href = "http://pledge.wprb.com">donate to wprb</a><br>
</p>
</body>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-10029854-1']);
  _gaq.push(['_setDomainName', 'wprb.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</html>
